---
title: "Example Report"
subtitle: "To Err is Human: An Empirical Investigation"
output: 
  rmarkdown::html_vignette:
    # theme: flatly
    # toc: true
    # toc_float: true
    # toc_location: left
    df_print: paged
vignette: >
  %\VignetteIndexEntry{Example Report}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style>
  h2.na::before { content: '⚪️ '; }
  h2.fail::before { content: '⚫️ '; }
  h2.info::before { content: '🔵 '; }
  h2.red::before { content: '🔴 '; }
  h2.yellow::before { content: '🟡 '; }
  h2.green::before { content: '🟢 '; }
</style>

::: {.column-margin}
🟢 no problems detected;<br>
🟡 something to check;<br>
🔴 possible problems detected;<br>
🔵 informational only;<br>
⚪️ not applicable;<br>
⚫️ check failed
:::

## Exact P-Values {.red}

You may have reported some imprecise p-values

|text    |p_comp | p_value|section | div|  p|  s|
|:-------|:------|-------:|:-------|---:|--:|--:|
|p > .05 |>      |    0.05|results |   3|  2|  2|

Showing 1 of 1 rows

## Marginal Significance {.red}

You described effects as marginally/borderline/close to significant. It is better to write 'did not reach the threshold alpha for significance'.

|text                                                                                                                                                                                                                                                             |section  | div|  p|  s|
|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------|---:|--:|--:|
|The paper shows examples of (1) open and closed OSF links; (2) citation of retracted papers; (3) missing/mismatched citations and references; (4) imprecise reporting of p-values; and (5) use of "marginally significant" to describe non-significant findings. |abstract |   0|  1|  3|
|On average researchers in the experimental condition found the app marginally significantly more useful (M = 5.06) than researchers in the control condition found the checklist (M = 4.5), t(97.2) = -1.96, p = 0.152.                                          |results  |   3|  2|  1|

Showing 2 of 2 rows

## Missing Effect Sizes {.red}

No effect sizes were detected for any t-tests or F-tests. The Journal Article Reporting Standards state effect sizes should be reported.

|text                                                                                                                                                                                                                    | div|  p|  s|test   |test_text       |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---:|--:|--:|:------|:---------------|
|On average researchers in the experimental (app) condition made fewer mistakes (M = 9.12) than researchers in the control (checklist) condition (M = 10.9), t(97.7) = 2.9, p = 0.005.                                   |   3|  1|  2|t-test |t(97.7) = 2.9   |
|On average researchers in the experimental condition found the app marginally significantly more useful (M = 5.06) than researchers in the control condition found the checklist (M = 4.5), t(97.2) = -1.96, p = 0.152. |   3|  2|  1|t-test |t(97.2) = -1.96 |

Showing 2 of 2 rows

## StatCheck {.red}

We detected possible errors in test statistics

|   |test_type |  df2|test_comp | test_value|p_comp | reported_p| computed_p|raw                        |error |decision_error |one_tailed_in_txt | apa_factor|text                                                                                                                                                                                                                    |section | div|  p|  s|
|:--|:---------|----:|:---------|----------:|:------|----------:|----------:|:--------------------------|:-----|:--------------|:-----------------|----------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------|---:|--:|--:|
|2  |t         | 97.2|=         |      -1.96|=      |      0.152|  0.0528594|t(97.2) = -1.96, p = 0.152 |TRUE  |FALSE          |FALSE             |          1|On average researchers in the experimental condition found the app marginally significantly more useful (M = 5.06) than researchers in the control condition found the checklist (M = 4.5), t(97.2) = -1.96, p = 0.152. |results |   3|  2|  1|

Showing 1 of 1 rows

## Check Status of OSF Links {.red}

We detected closed OSF links

|text         |section | div|  p|  s|osf_id |osf_type |public |name   |description |category |registration |preprint |parent |project |status |
|:------------|:-------|---:|--:|--:|:------|:--------|:------|:------|:-----------|:--------|:------------|:--------|:------|:-------|:------|
|osf.io/5tbm9 |method  |   2|  1|  2|5tbm9  |private  |FALSE  |NA     |NA          |NA       |NA           |NA       |NA     |NA      |closed |
|osf.io/5tbm9 |results |   3|  1|  1|5tbm9  |private  |FALSE  |NA     |NA          |NA       |NA           |NA       |NA     |NA      |closed |
|osf.io/629bx |results |   3|  1|  1|629bx  |nodes    |TRUE   |Public |            |         |FALSE        |FALSE    |cxjg4  |cxjg4   |open   |

Showing 3 of 3 rows

## RetractionWatch {.yellow}

You cited some papers in the Retraction Watch database (as of 2025-05-20). These may be retracted, have corrections, or expressions of concern.

|bib_id |ref                                                                                                                                                                                                                        |doi                      |bibtype |title                                                                 |journal               |year |authors                |retractionwatch |text                                                                                                                                                                          |
|:------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------|:-------|:---------------------------------------------------------------------|:---------------------|:----|:----------------------|:---------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|b0     |Gino F, Wiltermuth SS (2014). “Retracted: Evil Genius? How Dishonesty Can Lead to Greater Creativity.” _Psychological Science_, *25*(4), 973-981. doi:10.1177/0956797614520714 <https://doi.org/10.1177/0956797614520714>. |10.1177/0956797614520714 |Article |Retracted: Evil Genius? How Dishonesty Can Lead to Greater Creativity |Psychological Science |2014 |F Gino, S S Wiltermuth |Retraction      |Although intentional dishonestly might be a successful way to boost creativity (Gino & Wiltermuth, 2014), it is safe to say most mistakes researchers make are unintentional. |

Showing 1 of 1 rows

## Reference Consistency {.red}

This module relies on Grobid correctly parsing the references. There may be some false positives.

There are references that are not cited or citations that are not referenced

|bib_id         |ref                                                                                                                                                         |doi                |bibtype |title                                     |journal             |year |authors |missing   |
|:--------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------|:-------|:-----------------------------------------|:-------------------|:----|:-------|:---------|
|(Smithy, 2020) |From a human factors perspective, human error is a symptom of a poor design (Smithy, 2020).                                                                 |NA                 |NA      |NA                                        |NA                  |NA   |NA      |reference |
|b1             |Smith F (2021). “Human error is a symptom of a poor design.” _Journal of Journals_, *0*(0), 0. doi:10.0000/0123456789 <https://doi.org/10.0000/0123456789>. |10.0000/0123456789 |Article |Human error is a symptom of a poor design |Journal of Journals |2021 |F Smith |citation  |

Showing 2 of 2 rows
